## Convolutional Neural Network in mnist handwritten dataset

### DigitReconizer Kaggle

In [1]:
#importing libraries
import keras
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation, Flatten
from keras.layers.convolutional import Convolution2D, MaxPooling2D
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

Using TensorFlow backend.


In [2]:
data = pd.read_csv('mnist_dataset_kaggle/train.csv')
data.head()


label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 785 columns]

In [3]:
print(data.shape)
len(data)

(42000, 785)


42000

In [5]:
#storing pixel array in form length, width and channel in df_x
df_x = data.iloc[:, 1:].values.reshape(len(data), 28, 28, 1)

#storing the labels in y
y = data.iloc[:, 0].values

In [68]:
#converting labels to categorical features

df_y = keras.utils.to_categorical(y, num_classes=10)
df_y

array([[ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [7]:
df_x = np.array(df_x)
df_y = np.array(df_y)

In [8]:
#labels
y

array([1, 0, 1, ..., 7, 6, 9])

In [9]:
#categorical Labels
df_y

array([[ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [10]:
df_x.shape

(42000, 28, 28, 1)

In [11]:
df_y.shape

(42000, 10)

In [12]:
#test train split
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.20, random_state=4)

In [13]:
x_train.shape

(33600, 28, 28, 1)

In [14]:
x_test.shape

(8400, 28, 28, 1)

In [15]:
model = Sequential()
model.add(Convolution2D(32, 3, data_format='channels_last', activation='relu', input_shape=(28, 28, 1)))
model.add(MaxPooling2D(pool_size=(2,2)))
# Convolution
model.add(Convolution2D(filters=64, kernel_size=(3,3), strides=(2,2)))
#ReLU
model.add(Activation('relu'))
# Pooling
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(100))
#model.add(Dropout(0.2))
model.add(Activation('relu'))
model.add(Dense(10))
model.add(Activation('softmax'))

In [16]:
EPOCHS = 20

In [17]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 13, 13, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 6, 6, 64)          18496     
_________________________________________________________________
activation_1 (Activation)    (None, 6, 6, 64)          0         
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 3, 3, 64)          0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 576)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 100)               57700     
__________

In [18]:
model.compile(loss='categorical_crossentropy', optimizer='adadelta', metrics=['accuracy'])

In [19]:
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=EPOCHS)

Train on 33600 samples, validate on 8400 samples
Epoch 1/20
33600/33600 [==============================] - 24s 725us/step - loss: 1.2810 - acc: 0.8370 - val_loss: 0.2219 - val_acc: 0.9387
Epoch 2/20
33600/33600 [==============================] - 23s 676us/step - loss: 0.1311 - acc: 0.9608 - val_loss: 0.1392 - val_acc: 0.9605
Epoch 3/20
33600/33600 [==============================] - 22s 654us/step - loss: 0.0811 - acc: 0.9749 - val_loss: 0.1104 - val_acc: 0.9707
Epoch 4/20
33600/33600 [==============================] - 22s 653us/step - loss: 0.0574 - acc: 0.9817 - val_loss: 0.1095 - val_acc: 0.9692
Epoch 5/20
33600/33600 [==============================] - 22s 651us/step - loss: 0.0420 - acc: 0.9863 - val_loss: 0.0998 - val_acc: 0.9757
Epoch 6/20
33600/33600 [==============================] - 23s 681us/step - loss: 0.0314 - acc: 0.9897 - val_loss: 0.1038 - val_acc: 0.9750
Epoch 7/20
33600/33600 [==============================] - 24s 727us/step - loss: 0.0248 - acc: 0.9921 - val_loss: 0.0

In [44]:
model.save_weights('englishdigitclassifiermnistcnn.h5')

In [45]:
model.load_weights('englishdigitclassifiermnistcnn.h5')

### Testing

In [46]:
data = pd.read_csv('mnist_dataset_kaggle/test.csv')
data.head()


pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 784 columns]

In [47]:
data.shape

(28000, 784)

In [48]:
#To Test whole 

In [49]:
test_x = data.iloc[:,:].values.reshape(len(data), 28, 28, 1)
test_x.shape

(28000, 28, 28, 1)

In [50]:
test_x = np.array(test_x)

In [51]:
test_x.shape

(28000, 28, 28, 1)

In [52]:
prediction = model.predict(test_x)

In [53]:
prediction.shape

(28000, 10)

In [54]:
prediction = np.argmax(prediction, axis=1)
prediction

array([2, 0, 9, ..., 3, 9, 2])

In [55]:
prediction.shape

(28000,)

In [72]:
list(range(1, len(prediction)+1))

[1]

In [56]:
df = pd.DataFrame({
    'ImageId' : list(range(1,len(prediction)+1)),
    'Label' : prediction
})

df.to_csv("submission_raju_digitrecog_se.csv", index=False, header=True)